/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/connect/token": {
    post: operations["post-connect-token"];
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type external = Record<string, never>;

export type operations = {

  "post-connect-token": {
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @default wakanim.android.test2 */
          client_id?: string;
          /** @default password */
          grant_type?: string;
          /** @default code+id_token+token */
          response_type?: string;
          /** @default sypzbgkAPqTd9qrZ12oP */
          client_secret?: string;
          username?: string;
          password?: string;
          /** @default email+openid+profile+offline_access+read */
          scope?: string;
          /** @default wakanimandroidapp://callback */
          redirect_uri?: string;
          /** Format: uuid */
          nonce?: string;
          /** Format: uuid */
          state?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
        };
      };
    };
  };
};
